<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PC</name>
   <tag></tag>
   <elementGuidId>695ade75-3513-4e3e-8e4b-53ea6189c6ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnSteam']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSteam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31e8e814-5f48-4cdf-b379-ceb8c13d207d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>66fab6ba-096f-468d-a2dd-8b2f152d3af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signupPlat pc</value>
      <webElementGuid>2e5c379a-a9a2-4331-bbca-bbb4ec8731ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSteam</value>
      <webElementGuid>8056756c-2725-4da2-ae4c-65df1c100942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plat</name>
      <type>Main</type>
      <value>pc</value>
      <webElementGuid>4582176c-458b-496b-8304-f45df74739c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            PC
        </value>
      <webElementGuid>fe60a728-1949-45e7-ba39-cdcd0ba0ddb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSteam&quot;)</value>
      <webElementGuid>67f5d4ea-387a-4d68-b5eb-c273e93d1ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnSteam']</value>
      <webElementGuid>a43c8820-03c7-4df1-a08c-32b6dc4e1621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signupPlatforms']/a</value>
      <webElementGuid>29391458-2aba-4989-b57d-dc40f17abde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What will you be playing on?'])[1]/following::a[1]</value>
      <webElementGuid>aaecb921-ac29-4c59-a24e-b29748fe78f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PlayStation'])[1]/preceding::a[1]</value>
      <webElementGuid>5b705e20-fb7d-4135-9a18-c60909480682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>0befcff7-4de1-4e10-a3e3-70dcbefd421b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>eda0dd73-7de9-4a31-84a5-635436453c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btnSteam' and (text() = '
            
            PC
        ' or . = '
            
            PC
        ')]</value>
      <webElementGuid>30a5f50d-ee5c-4915-a412-33f860594ab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
