<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PLAY FREE NOW</name>
   <tag></tag>
   <elementGuidId>824d0d81-8fc9-4f67-b932-a4ab85d2ddf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnPlay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnPlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0851bf71-a5aa-448b-9cfd-0642403c33cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>playFreeNow</value>
      <webElementGuid>feaab9c5-c7ff-4c1a-810f-cff4b8adcf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPlay</value>
      <webElementGuid>3f381d2c-997c-4b7c-9f50-3ed659759185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cfe5dda0-d557-4943-8958-11e53bfff2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY FREE NOW</value>
      <webElementGuid>a630fb87-d98a-4a18-85d9-d76bc4aa9c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPlay&quot;)</value>
      <webElementGuid>5f1da06a-a5e2-40b9-b878-4b488f5b7446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnPlay']</value>
      <webElementGuid>5598e123-9631-4c04-af02-71eef16a0e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'PLAY FREE NOW')])[2]</value>
      <webElementGuid>d32fe696-d2f6-4d20-99c6-df32739c60df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Українська'])[1]/following::a[4]</value>
      <webElementGuid>e825b95c-09ef-41a0-b08f-897e1cb9f948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體中文'])[1]/following::a[5]</value>
      <webElementGuid>d835ed0a-d6d4-4e88-bce4-444648417cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHOOSE YOUR WARFRAME'])[1]/preceding::a[2]</value>
      <webElementGuid>2ebed948-aad4-45ad-ae26-b7b790756ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ash'])[1]/preceding::a[2]</value>
      <webElementGuid>ea28c708-7264-45d3-9fd4-26b5f016048b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>48e2af4d-0ef2-4d44-9e6e-6699c3cab65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[3]/div/a</value>
      <webElementGuid>c66a66ea-ad2f-4510-8104-f8cece0eadf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnPlay' and @href = '#' and (text() = 'PLAY FREE NOW' or . = 'PLAY FREE NOW')]</value>
      <webElementGuid>55534794-1762-48f3-ac7c-d6702bdf14e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
