<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_opt_in_newsletter_check</name>
   <tag></tag>
   <elementGuidId>bfa69b39-c703-4e4f-b9b5-d005e4c17551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='opt_in_newsletter_check']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#opt_in_newsletter_check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2400525c-d34e-431e-9c73-2f8c0a5fced6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>67211ae8-3343-4eaf-ad74-bdda6f8a3901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opt_in_newsletter_check</value>
      <webElementGuid>94639871-0ed8-4bf3-803a-dd2048045d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkNews</value>
      <webElementGuid>eaff786a-8659-4770-9fff-ab4cf2be9a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>opt_in_newsletter_check</value>
      <webElementGuid>7b97963a-26a1-48e7-8ebd-05da381f7d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>832fe265-67b8-4429-b9fb-7e327ab796e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt_in_newsletter_check&quot;)</value>
      <webElementGuid>f766f4a7-4043-4356-bfef-81fd621a80bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='opt_in_newsletter_check']</value>
      <webElementGuid>9683c7b3-7990-4c5c-9ad6-439250d34d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='opt-in-newsletter']/input</value>
      <webElementGuid>1a8db3dd-445b-492e-89a9-570cf6fd02fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[6]/input</value>
      <webElementGuid>2a984bd2-a4d0-4610-b962-edb095e29202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'opt_in_newsletter_check' and @name = 'opt_in_newsletter_check']</value>
      <webElementGuid>8b9b74fa-6c01-4793-b5e0-5a1d197aedd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
