<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_password_confirm</name>
   <tag></tag>
   <elementGuidId>1e8f4145-77e4-42f5-a379-18ddcc50fd64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password_confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a8bf50f-2e00-49df-bcdb-79ed0ddc0741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7af5ff21-bd33-48d1-9a66-8a8813632345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_confirm</value>
      <webElementGuid>6eef621d-0ed7-4f97-9762-ff0d6bf175aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_confirm</value>
      <webElementGuid>5bafdb93-2a87-435d-80bc-91ebe3ca8213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-full-width form-text fldConfirmpswd</value>
      <webElementGuid>3669b576-ed46-47ab-a0be-bfe670cfdc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>70d6d36b-04ad-4db9-ae56-25ca57edb517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_confirm&quot;)</value>
      <webElementGuid>8dc4aec6-19e0-47a2-8efb-6b420bf90355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_confirm']</value>
      <webElementGuid>f4ac71ea-b5ff-4ac7-80e8-817f29265369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='confirm-password']/input</value>
      <webElementGuid>b8fd93d7-9c29-4104-a4bc-2ae00f934b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/input</value>
      <webElementGuid>9b9bea5b-9acc-4f6e-a520-0919c364b034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password_confirm' and @id = 'password_confirm' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>b5174675-73c7-4c45-ae4c-1f81f81f7b92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
