<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Your confirmed password doesn,_7d1f74</name>
   <tag></tag>
   <elementGuidId>d2dbc724-69cc-4666-9e55-32e0a1aaef54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='opt_in_newsletter_check']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#opt_in_newsletter_check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f690f1f0-0d1a-47e0-9d34-c8c3ce219711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>21e825da-7adb-4177-8b42-db0a5087c3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opt_in_newsletter_check</value>
      <webElementGuid>4bfbd9d8-50ac-4955-86d6-dba6583ee6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkNews</value>
      <webElementGuid>b554c778-40e7-4d71-a3be-2f29ba05e2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>opt_in_newsletter_check</value>
      <webElementGuid>797b987e-32ac-4760-ba99-8af772fbc225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9824ea7a-1ebe-4985-a5be-f55f995306a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt_in_newsletter_check&quot;)</value>
      <webElementGuid>7cd6cf89-55d1-45e3-a1c8-a3a27ca1439b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='opt_in_newsletter_check']</value>
      <webElementGuid>ef9e7ba6-1a4a-4890-a6b4-7325f39f1529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='opt-in-newsletter']/input</value>
      <webElementGuid>f22815bf-f7a4-4898-b799-3fda61a06f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[6]/input</value>
      <webElementGuid>0e83298e-f882-429e-8826-b68af36d1b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'opt_in_newsletter_check' and @name = 'opt_in_newsletter_check']</value>
      <webElementGuid>6e0cdbbe-c939-4f36-b7b4-f0be7499d070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
