<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Email_email_confirm</name>
   <tag></tag>
   <elementGuidId>060dff16-33f7-4ed1-9806-386c4684d04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email_confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e150087-9da8-463e-b6a1-e66e3efad113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8c491fd6-c00b-46ac-b107-8bdca674569b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_confirm</value>
      <webElementGuid>dfb9c528-c6f8-44a4-850b-593c94c34845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_confirm</value>
      <webElementGuid>18818e41-d95f-44b9-b4b0-24873d3e12a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Email</value>
      <webElementGuid>8880cb27-d0ea-43a4-92a7-d1717218181a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-full-width form-text fldConfirmmail</value>
      <webElementGuid>b094df29-3474-473c-852b-9cf25420a258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_confirm&quot;)</value>
      <webElementGuid>1dd8224c-e788-4f6b-a0b6-d1aaacaf2e87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_confirm']</value>
      <webElementGuid>005c4b3c-538c-4f6c-8399-767bfccf3b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='confirm-email']/input</value>
      <webElementGuid>d9550c18-5d30-40a2-8b2f-286301c455a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input</value>
      <webElementGuid>06037899-e85c-413a-a732-75a8521d8dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email_confirm' and @id = 'email_confirm' and @placeholder = 'Confirm Email']</value>
      <webElementGuid>e3d079ad-5e9e-4aa1-b3e9-c17dc74c6231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
